@label=test

### Healthcheck
GET {{host}}/api/healthcheck

### Get info
GET {{host}}/api/v1/info

### Echo simple HTTP request
POST {{host}}/api/v1/echo

{
    "msg": "Hello, world!"
}

### Get data
GET {{host}}/api/v1/data

### Post data
POST {{host}}/api/v1/data/test
Content-Type: application/json

{
    "msg": "Hello, world!"
}

### Get users
GET {{host}}/api/v1/users

### Create user
POST {{host}}/api/v1/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test@test.com"
}

### OpenAPI Specification
GET {{host}}/openapi.json


###
